assets/scss/common.scss
pages/venue.vue

Add getting there info

---

pages/participate.vue

Add tickets section

---

components/BlockHeaderPlain.vue
pages/participate.vue
pages/sprint.vue

Start for the sprint page

---

pages/venue.vue

cc @SylvainCorlay 
This is for the "Venue Information" content only.

Add conference center to the venue page

---

pages/venue.vue

Fix BCC address

---

assets/scss/_settings.scss
assets/scss/common.scss
components/BlockHeader.vue
components/BlockHeaderPlain.vue
pages/sprint.vue

Fixes #15.
Thanks @deeplook for the content!

Add directions for the sprints venue

---

components/BlockHeaderPlain.vue
components/MenuContent.vue
pages/about.vue
pages/sustainability.vue

There is a bit of in-consistency in naming of sustainability and eco-friendly, not sure if that matters.

Add sustainability

---

components/MenuBar.vue

Add youtube channel link

---

components/MenuContent.vue
pages/venue.vue

Add hotel and local info

---

pages/venue.vue

According to the feedback on the original document: this section is more likely to be used the most by the attendees.

Move restaurant section to the top

---

components/DesktopFooter.vue
components/MenuBar.vue
pages/privacy.vue

This is a copy of https://numfocus.org/privacy-policy with modifications as suggested by Jim Weiss

fill in privacy policy, solved #43

---

pages/sprint.vue

Add link to JupyterCon Twitter on the sprints page

---

pages/codeofconduct.vue
pages/privacy.vue
pages/sponsors.vue
pages/sustainability.vue
pages/venue.vue

Some fixes in the content

---

package.json

Better website description

---

pages/venue.vue

Add country to the venue address

---

components/Committee.vue

shorten Tania's bio

---

components/BlockAbout.vue

Remove learn more

---

components/Committee.vue

shorten Paco's bio

---

pages/about.vue
pages/participate.vue

Adding blurbs for diversity and CoC

---

components/DesktopSponsors.vue
pages/index.vue

Use h1 for Participate and sponsors sections

---

pages/privacy.vue

Fix Sylvain’s email.

---

pages/privacy.vue

Fix Sylvain’s obfuscated email address on the privacy page.

---

pages/venue.vue

In particular, this says we'll post more details soon about the service and how to sign up for it.

Update childcare info to what we know currently.

---

assets/scss/custom.sass
pages/about.vue
pages/venue.vue

fix: legability of links on dark background

---

pages/sponsors.vue

@SylvainCorlay 
added link to Community Sponsor Form for other groups to contact us

Comm Sponsors: added form link

---

pages/diversity.vue

Add email to connect with the JupyterCon Diversity Committee.

Add email to connect with the JupyterCon Diversity Committee

---

pages/participate.vue

1. Adding a link to the Diversity and Financial Aid application form
2. Editing the page content to indicate that applications are now being accepted
3. Reformatting the info about the important dates in regards of this application to match the rest of the website

Update info about the scholarship application, minor formatting fixes

---

pages/covid-19-statement.vue
pages/talk-poster-cfp.vue
pages/tutorial-cfp.vue

This notes that we are temporarily suspending ticket sales and the cfp.

Update COVID-19 statement

---

components/BlockHeader.vue
pages/participate.vue
pages/talk-poster-cfp.vue
pages/tutorial-cfp.vue

Shift site to post-cfp phase, removing language about proposing a tutorial, etc.

---

components/BlockHeader.vue
pages/sprint.vue

Let's wait for the ticket and the tweets to be ready before the deployment (cc @captainsafia)

Update sprint submission deadline

---

pages/sponsors.vue

added twitter, website,etc (new fields) for community sponsors

---

pages/participate.vue

Here is the acknowledgement text:
> We would like to thank all of the community reviewers who reviewed talk, poster, and tutorial proposals. Listed below are the reviewers who completed all of their requested reviews by the deadline. Thank you!

Add a list of community reviewers who completed their reviews by the deadline

---

assets/scss/footer.sass
components/DesktopFooter.vue

Add social links to the footer

---

assets/scss/footer.sass

Add spacing to the items in the footer

---

pages/sponsors.vue

Follow-up https://github.com/jupytercon/jupytercon2020-website/pull/216#issuecomment-693252813

Edit InfuseAI description

---

components/MenuContent.vue

- Add a link to the schedule
- Remove the temp list of talks

Add the schedule

---

components/DesktopSponsors.vue
nuxt.config.js
package-lock.json
package.json
pages/sponsors.vue
plugins/vue-carousel.js
store/index.js

Add a carousel with the sponsors on the main page

---

components/DesktopSponsors.vue

Change color of Sponsors heading to orange

---

components/BlockHeader.vue

Add talks and tutorials buttons to the front page

---

pages/attendee-experience.vue

Add JupyterHub resources to Attendee Experience

---

components/BlockHeader.vue

This makes the videos more prominent for people at the website.

Change front page "register" button to "videos"
